name: Test-Evaluate-Deploy Prompts with Promptflow

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '*/*'
    paths:
      - 'flow/**'

env: 
  GROUP: ${{secrets.GROUP}}
  WORKSPACE: ${{secrets.WORKSPACE}}
  SUBSCRIPTION: ${{secrets.SUBSCRIPTION}}
  RUN_NAME: web_classification_variant_1_20230816_215600_605116
  EVAL_RUN_NAME: classification_accuracy_eval_default_20230821_111809_077086
  COMPUTE_NAME_PRE: llm-compute
  MANAGED_IDENTITY_NAME: test-promptflow-msi
  RUNTIME_NAME_PRE: llm-runtime
  LOCATION: germanywestcentral
  MODEL_NAME:  web-classification-model
  SP_USER: ${{secrets.SP_USER}}
  SP_PASS: ${{secrets.SP_PASS}}
  SP_TENANT: ${{secrets.SP_TENANT}}
  ENDPOINT_NAME: demo-endpoint
  DEPLOYMENT_NAME: deployment

jobs:
  evaluation:
    runs-on: ubuntu-latest
    outputs:
      deployModel: ${{ steps.EvalResult.outputs.eval_result }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: |
        az login --service-principal -u ${{env.SP_USER}} -p ${{env.SP_PASS}} --tenant ${{env.SP_TENANT}}

  deployment:
    runs-on: ubuntu-latest
    needs:
      - evaluation
    if: github.ref == 'refs/heads/main' && needs.evaluation.outputs.deployModel == 'true'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      run: |
        az login --service-principal -u ${{env.SP_USER}} -p ${{env.SP_PASS}} --tenant ${{env.SP_TENANT}}
        az account set -s ${{env.SUBSCRIPTION}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: Install promptflow
      run: pip install -r flow/promptflow/web-classification/requirements.txt
    - name: Register promptflow model
      run: az ml model create --file flow/promptflow/deployment/model.yaml  -g ${{env.GROUP}} -w ${{env.WORKSPACE}}
    - name: Set Endpoint Name
      run: |
        echo "${{ github.run_id }}"
        unique_identifier=${{ github.run_id }}
        unique_identifier_first_10="${unique_identifier:0:10}"

        new_endpoint_name="${{env.ENDPOINT_NAME}}$unique_identifier_first_10"
        echo $new_endpoint_name

        echo "ENDPOINT_NAME=$new_endpoint_name" >> "$GITHUB_ENV"

    - name: Setup endpoint
      run: |
        az ml online-endpoint create --file flow/promptflow/deployment/endpoint.yaml  --name ${{env.ENDPOINT_NAME}} -g ${{env.GROUP}} -w ${{env.WORKSPACE}}
    - name: Check the status of the endpoint
      run: az ml online-endpoint show -n ${{env.ENDPOINT_NAME}} -g ${{env.GROUP}} -w ${{env.WORKSPACE}}
    - name: Update deployment PRT_CONFIG variable
      run: |
        PRT_CONFIG_OVERRIDE=deployment.subscription_id=${{ env.SUBSCRIPTION }},deployment.resource_group=${{ env.GROUP }},deployment.workspace_name=${{ env.WORKSPACE }},deployment.endpoint_name=${{ env.ENDPOINT_NAME }},deployment.deployment_name=${{ env.DEPLOYMENT_NAME }}
        sed -i "s/PRT_CONFIG_OVERRIDE:.*/PRT_CONFIG_OVERRIDE: $PRT_CONFIG_OVERRIDE/g" flow/promptflow/deployment/deployment.yaml
    - name: Setup deployment
      run: az ml online-deployment create --file flow/promptflow/deployment/deployment.yaml --endpoint-name ${{env.ENDPOINT_NAME}} --all-traffic -g ${{env.GROUP}} -w ${{env.WORKSPACE}}
    - name: Check the status of the deployment
      run: az ml online-deployment get-logs --name test-1 --endpoint-name ${{env.ENDPOINT_NAME}} -g ${{env.GROUP}} -w ${{env.WORKSPACE}}











