name: Test and Evaulate Prompts with Promptflow

on:
  workflow_dispatch:
  push:
    branches: [ feature/cenkOpenAI ]

env: 
  GROUP: ${{secrets.GROUP}}
  WORKSPACE: ${{secrets.WORKSPACE}}
  SUBSCRIPTION: ${{secrets.SUBSCRIPTION}}
  RUN_NAME: web_classification_variant_1_20230816_215600_605116
  EVAL_RUN_NAME: classification_accuracy_eval_default_20230821_111809_077086
  COMPUTE_NAME: llm-devops-compute-source
  MANAGED_IDENTITY_NAME: test-promptflow-msi
  RUNTIME_NAME: llm-devops-runtime

jobs:
  login-and-run-and-evalpf:
    runs-on: ubuntu-latest 
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: Install promptflow
      run: pip install -r flow/promptflow/web-classification/requirements.txt
    - name: Create Test Compute Source
      run: |
        az account set -s ${{env.SUBSCRIPTION}}
        az identity create -g ${{env.GROUP}} -n ${{env.MANAGED_IDENTITY_NAME}} --query "id"
        um_details=$(az identity show -g ${{env.GROUP}} -n ${{env.MANAGED_IDENTITY_NAME}} --query "[id, clientId, principalId]")
        user_managed_id="$(echo $um_details | jq -r '.[0]')"
        principalId="$(echo $um_details | jq -r '.[2]')"
        az role assignment create --assignee-object-id $principalId --assignee-principal-type ServicePrincipal --role "AzureML Data Scientist" --scope "/subscriptions/${{env.SUBSCRIPTION}}/resourcegroups/${{env.GROUP}}/providers/Microsoft.MachineLearningServices/workspaces/${{env.WORKSPACE}}"
        az ml compute create --name ${{env.COMPUTE_NAME}} --size Standard_DS1_v2 --identity-type UserAssigned --type ComputeInstance --resource-group ${{env.GROUP}} --workspace-name ${{env.WORKSPACE}} --user-assigned-identities $user_managed_id
        access_token=$(az account get-access-token | jq -r ".accessToken")
        runtime_url_post=$(echo "https://ml.azure.com/api/$location/flow/api/subscriptions/${{env.SUBSCRIPTION}}/resourceGroups/${{env.GROUP}}/providers/Microsoft.MachineLearningServices/workspaces/${{env.WORKSPACE}}/FlowRuntimes/${{env.RUNTIME_NAME}}?asyncCall=true")
        curl --request POST \
          --url "$runtime_url_post" \
          --header "Authorization: Bearer $access_token" \
          --header 'Content-Type: application/json' \
          --data "{
          \"runtimeType\": \"ComputeInstance\",
          \"computeInstanceName\": \"${{env.COMPUTE_NAME}}\",
        }"
