name: Test and Evaluate Prompts with Promptflow

on:
  workflow_dispatch:
  push:
    branches: [ feature/cenkOpenAI ]

env: 
  GROUP: ${{secrets.GROUP}}
  WORKSPACE: ${{secrets.WORKSPACE}}
  SUBSCRIPTION: ${{secrets.SUBSCRIPTION}}
  RUN_NAME: web_classification_variant_1_20230816_215600_605116
  EVAL_RUN_NAME: classification_accuracy_eval_default_20230821_111809_077086
  COMPUTE_NAME: llm-compute101
  MANAGED_IDENTITY_NAME: test-promptflow-msi
  RUNTIME_NAME: llm-runtime101
  LOCATION: germanywestcentral
  MODEL_NAME:  web-classification-model
  SP_USER: ${{secrets.SP_USER}}
  SP_PASS: ${{secrets.SP_PASS}}
  SP_TENANT: ${{secrets.SP_TENANT}}

jobs:
  login-and-run-and-evalpf:
    runs-on: ubuntu-latest 
    steps:
    - name: Check out repo
      uses: actions/checkout@v2